version: '2'
services:
  api1:
    build: api_1/
    environment:
      - PORT=5000
    ports:
      - 5000

  lb1:
    image: dockercloud/haproxy
    ports:
      - "5000:80"
    links:
      - api1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api2:
    build: api_2/
    environment:
      - PORT=3000
    ports:
      - 3000

  lb2:
    image: dockercloud/haproxy
    ports:
      - "3000:80"
    links:
      - api2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
